# Generated by Django 4.2.3 on 2023-08-07 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('invoice_no', models.IntegerField(verbose_name='Invoice Number')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Detail',
            fields=[
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='invoice_details', serialize=False, to='invoice.invoice')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Invoice description')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity of items')),
                ('unit_price', models.FloatField(verbose_name='Unit Price')),
            ],
        ),
    ]
